title: The Ultimate Nuzlocke Ruleset
description: The best assortment of rules for a Nuzlocke run, or at least my own definition of it
author:
  name: Adrian Castro
  email: adrifcastr@gmail.com
markdown: GFM
remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    github: castdrian
    twitter: castdrian
