title: The Ultimate Nuzlocke Ruleset
description: The best assortment of rules for a Nuzlocke run, or at least my own definition of it
markdown: GML
theme: minima
twitter_username: castdrian
github_username: castdrian
